application: grammar-analyzer
version: 0c
runtime: python
api_version: 1

handlers:
- url: /style.css
  static_files: style.css
  upload: style.css

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /(.*\.js)
  static_files: \1
  upload: (.*\.js)

- url: /(test/.*)
  static_files: \1
  upload: (test/.*)

- url: /.*
  static_files: index.html
  upload: index.html